export const mockCurrentAmbassador = {
  id: "amb-001",
  full_name: "S.E. M. Jean-Pierre Mbadinga",
  email: "ambassador@gabonid.ga",
  role: "ambassador",
  active: true,
};

export const mockAdmins = [
  {
    id: "adm-001",
    name: "Carine Nguema",
    email: "carine.nguema@gabonid.ga",
    role: "admin",
    active: true,
  },
  {
    id: "adm-002",
    name: "Patrick Moussavou",
    email: "patrick.moussavou@gabonid.ga",
    role: "admin",
    active: true,
  },
  {
    id: "adm-003",
    name: "Aline Obiang",
    email: "aline.obiang@gabonid.ga",
    role: "admin",
    active: false,
  },
  {
    id: "amb-001",
    name: "S.E. M. Jean-Pierre Mbadinga",
    email: "ambassador@gabonid.ga",
    role: "ambassador",
    active: true,
  },
];

export const mockStudents = [
  {
    id: "cit-001",
    full_name: "Claire Nze",
    email: "claire.nze@student.com",
    passport: "GA-2024-08712",
    nip: "NIP-GA-100245",
    university: "University of Rwanda",
    program: "Master Informatique",
    location: "Kigali",
    phone: "+250 780 111 001",
    emergency_contact: "Marc Nze",
    status: "active",
    checkin_status: "validated",
    residence_status: "updated",
  },
  {
    id: "cit-002",
    full_name: "Paul Obame",
    email: "paul.obame@student.com",
    passport: "GA-2023-04291",
    nip: "NIP-GA-100246",
    university: "Kigali Independent University",
    program: "Licence Génie Civil",
    location: "Huye",
    phone: "+250 780 111 002",
    emergency_contact: "Aline Obame",
    status: "active",
    checkin_status: "pending",
    residence_status: "updated",
  },
  {
    id: "cit-003",
    full_name: "Marie Ndong",
    email: "marie.ndong@student.com",
    passport: "GA-2022-11034",
    nip: "NIP-GA-100247",
    university: "AUCA",
    program: "MBA Finance",
    location: "Kigali",
    phone: "+250 780 111 003",
    emergency_contact: "Jean Ndong",
    status: "active",
    checkin_status: "validated",
    residence_status: "updated",
  },
  {
    id: "cit-004",
    full_name: "Jean Moussavou",
    email: "jean.moussavou@student.com",
    passport: "GA-2024-09821",
    nip: "NIP-GA-100248",
    university: "University of Rwanda",
    program: "Médecine",
    location: "Huye",
    phone: "+250 780 111 004",
    emergency_contact: "Célestine Moussavou",
    status: "active",
    checkin_status: "pending",
    residence_status: "pending",
  },
  {
    id: "cit-005",
    full_name: "Aline Mba",
    email: "aline.mba@student.com",
    passport: "GA-2023-05518",
    nip: "NIP-GA-100249",
    university: "CMU Kigali",
    program: "Licence Droit",
    location: "Musanze",
    phone: "+250 780 111 005",
    emergency_contact: "Stéphane Mba",
    status: "flagged",
    checkin_status: "flagged",
    residence_status: "outdated",
  },
  {
    id: "cit-006",
    full_name: "Brice Essono",
    email: "brice.essono@student.com",
    passport: "GA-2024-07654",
    nip: "NIP-GA-100250",
    university: "University of Rwanda",
    program: "Licence Informatique",
    location: "Kigali",
    phone: "+250 780 111 006",
    emergency_contact: "Madeleine Essono",
    status: "active",
    checkin_status: "validated",
    residence_status: "updated",
  },
];

export const mockSOSCases = [
  {
    id: "sos-001",
    citizen_id: "cit-003",
    name: "Marie Ndong",
    location: "Kigali Centre",
    time: "Il y a 5 min",
    status: "active",
    bloodType: "A+",
    phone: "+250 780 111 003",
    emergency: "Jean Ndong (Père)",
    lat: -1.9403,
    lng: 29.8739,
    isStudent: true,
    passport: "GA-2022-11034",
    photo: null,
    created_at: "2026-03-31T10:25:00Z",
    reason: "Problème médical urgent",
    priority: "high",
  },
  {
    id: "sos-002",
    citizen_id: "cit-002",
    name: "Paul Obame",
    location: "Nyamirambo",
    time: "Il y a 12 min",
    status: "responding",
    bloodType: "O-",
    phone: "+250 780 111 002",
    emergency: "Aline Obame (Sœur)",
    lat: -1.9756,
    lng: 30.0344,
    isStudent: true,
    passport: "GA-2023-04291",
    photo: null,
    created_at: "2026-03-31T10:18:00Z",
    reason: "Perte de documents et besoin d'assistance",
    priority: "medium",
  },
  {
    id: "sos-003",
    citizen_id: "cit-005",
    name: "Aline Mba",
    location: "Musanze",
    time: "Il y a 1h",
    status: "resolved",
    bloodType: "B+",
    phone: "+250 780 111 005",
    emergency: "Stéphane Mba",
    lat: -1.4996,
    lng: 29.6344,
    isStudent: true,
    passport: "GA-2023-05518",
    photo: null,
    created_at: "2026-03-31T09:20:00Z",
    reason: "Urgence logement",
    priority: "medium",
  },
];

export const mockDocuments = [
  {
    id: "doc-001",
    citizen_id: "cit-003",
    title: "Passeport - Renouvellement",
    citizen: "Marie Ndong",
    status: "pending",
    created_at: "2026-03-25",
    blockchain_hash: null,
    signed_at: null,
    type: "passeport",
    category: "official",
  },
  {
    id: "doc-002",
    citizen_id: "cit-002",
    title: "Certificat de Naissance",
    citizen: "Paul Obame",
    status: "pending",
    created_at: "2026-03-22",
    blockchain_hash: null,
    signed_at: null,
    type: "certificat",
    category: "civil",
  },
  {
    id: "doc-003",
    citizen_id: "cit-001",
    title: "Licence ANBG",
    citizen: "Claire Nze",
    status: "flagged",
    created_at: "2026-03-19",
    blockchain_hash: "f7e6d5c4b3a29182736455463728192038475665748392010293847566758493",
    signed_at: "2026-03-20",
    type: "bourse",
    category: "education",
  },
  {
    id: "doc-004",
    citizen_id: "cit-006",
    title: "Attestation Consulaire",
    citizen: "Brice Essono",
    status: "signed",
    created_at: "2026-03-18",
    blockchain_hash: "a3f2b8c1d4e5f6789012345678abcdef01234567890abcdef1234567890abcdef",
    signed_at: "2026-03-19",
    type: "attestation",
    category: "consular",
  },
];

export const mockCheckins = [
  {
    id: "chk-001",
    citizen_id: "cit-004",
    name: "Jean Moussavou",
    semester: "S1 2026",
    created_at: "2026-03-15",
    status: "pending",
    location: "Kigali",
  },
  {
    id: "chk-002",
    citizen_id: "cit-003",
    name: "Marie Ndong",
    semester: "S1 2026",
    created_at: "2026-03-14",
    status: "validated",
    location: "Kigali",
  },
  {
    id: "chk-003",
    citizen_id: "cit-002",
    name: "Paul Obame",
    semester: "S1 2026",
    created_at: "2026-03-13",
    status: "pending",
    location: "Huye",
  },
  {
    id: "chk-004",
    citizen_id: "cit-005",
    name: "Aline Mba",
    semester: "S1 2026",
    created_at: "2026-03-12",
    status: "flagged",
    location: "Musanze",
  },
  {
    id: "chk-005",
    citizen_id: "cit-001",
    name: "Claire Nze",
    semester: "S1 2026",
    created_at: "2026-03-11",
    status: "validated",
    location: "Kigali",
  },
];

export const mockAuditLogs = [
  {
    id: "log-001",
    action: "Document signé",
    target_name: "Attestation Consulaire - Brice Essono",
    created_at: "2026-03-31T09:00:00Z",
    category: "documents",
    actor: "S.E. M. Jean-Pierre Mbadinga",
  },
  {
    id: "log-002",
    action: "Admin créé",
    target_name: "Carine Nguema",
    created_at: "2026-03-31T08:40:00Z",
    category: "admin",
    actor: "S.E. M. Jean-Pierre Mbadinga",
  },
  {
    id: "log-003",
    action: "SOS traité",
    target_name: "Paul Obame",
    created_at: "2026-03-31T08:10:00Z",
    category: "sos",
    actor: "Patrick Moussavou",
  },
  {
    id: "log-004",
    action: "Check-in validé",
    target_name: "Marie Ndong",
    created_at: "2026-03-30T17:20:00Z",
    category: "checkin",
    actor: "Carine Nguema",
  },
  {
    id: "log-005",
    action: "Message diffusé",
    target_name: "Tous les étudiants enregistrés",
    created_at: "2026-03-30T15:00:00Z",
    category: "messages",
    actor: "S.E. M. Jean-Pierre Mbadinga",
  },
];

export const mockGeoData = [
  { city: "Kigali", count: 320, percent: 58, color: "jaune" },
  { city: "Huye", count: 140, percent: 25, color: "emerald" },
  { city: "Musanze", count: 90, percent: 17, color: "gold" },
];

export const mockStats = [
  { label: "Total Enrôlés", value: "550", sub: "Citoyens actifs", color: "jaune" },
  { label: "Passeport", value: "68%", sub: "Identifiés", color: "emerald" },
  { label: "NIP", value: "32%", sub: "Identifiés", color: "gold" },
  { label: "Docs Certifiés", value: "1,480", sub: "Traités", color: "emerald" },
];